M48
; DRILL file {KiCad 9.0.3} date 2025-10-27T19:17:55+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-27T19:17:55+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
%
G90
G05
T1
X187.7Y-65.06
X187.7Y-67.6
X187.7Y-72.96
X187.7Y-75.5
M30
