M48
; DRILL file {KiCad 9.0.3} date 2025-11-17T14:32:01+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-17T14:32:01+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
%
G90
G05
T1
X52.16Y-49.65
X52.16Y-52.19
X52.16Y-54.73
X52.16Y-59.15
X52.16Y-61.69
X52.16Y-64.23
T2
X66.1Y-105.2
X73.6Y-105.2
M30
