M48
; DRILL file {KiCad 9.0.3} date 2025-10-29T14:16:56+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-29T14:16:56+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
%
G90
G05
T1
X107.05Y-66.56
X107.05Y-69.1
T2
X108.775Y-91.325
X108.775Y-98.825
M30
